Param(
    [Parameter(Mandatory = $false)]
    [string]$Remote = "",
    [Parameter(Mandatory = $false)]
    [int]$Commits = 12,
    [Parameter(Mandatory = $false)]
    [int]$MonthsBack = 3,
    [Parameter(Mandatory = $false)]
    [string]$Branch = "main",
    [Parameter(Mandatory = $false)]
    [string]$ChangeFile = "CHANGELOG.autogen.md"
)

function Write-Info($msg) {
    Write-Host "[INFO] $msg" -ForegroundColor Cyan
}
function Write-Warn($msg) {
    Write-Host "[WARN] $msg" -ForegroundColor Yellow
}
function Write-Err($msg) {
    Write-Host "[ERROR] $msg" -ForegroundColor Red
    exit 1
}

function Assert-Git() {
    $git = Get-Command git -ErrorAction SilentlyContinue
    if (-not $git) {
        Write-Err "Git is not installed or not in PATH."
    }
}

function Get-RandomDateBetween([DateTimeOffset]$Start, [DateTimeOffset]$End) {
    if ($End -le $Start) { return $Start }
    $rangeTicks = $End.UtcTicks - $Start.UtcTicks
    $rand = Get-Random -Minimum 0 -Maximum $rangeTicks
    return [DateTimeOffset]::FromUnixTimeMilliseconds((($Start.UtcDateTime.Ticks + $rand - 621355968000000000) / 10000))
}

function Get-RandomDates([DateTimeOffset]$Start, [DateTimeOffset]$End, [int]$Count) {
    $dates = New-Object System.Collections.Generic.List[DateTimeOffset]
    for ($i = 0; $i -lt $Count; $i++) {
        $dates.Add((Get-RandomDateBetween -Start $Start -End $End))
    }
    return $dates | Sort-Object
}

function Ensure-RepoInitialized() {
    $isRepo = $false
    try {
        git rev-parse --is-inside-work-tree *> $null
        if ($LASTEXITCODE -eq 0) { $isRepo = $true }
    } catch {
        $isRepo = $false
    }
    if (-not $isRepo) {
        Write-Info "Initializing new git repository..."
        git init | Out-Null
    } else {
        Write-Info "Existing git repository detected."
    }
}

Assert-Git

if ($Commits -lt 1) { Write-Err "Commits must be >= 1" }
if ($MonthsBack -lt 1) { Write-Err "MonthsBack must be >= 1" }

$now = [DateTimeOffset]::Now
$start = $now.AddMonths(-1 * $MonthsBack)

Ensure-RepoInitialized

# Make sure default branch name is as requested
git symbolic-ref --short HEAD *> $null
if ($LASTEXITCODE -ne 0) {
    Write-Info "Setting default branch to '$Branch'..."
    git checkout -b $Branch | Out-Null
} else {
    # Rename current branch if needed
    $current = (git symbolic-ref --short HEAD).Trim()
    if ($current -ne $Branch) {
        Write-Info "Renaming branch '$current' -> '$Branch'..."
        git branch -M $Branch
    }
}

# Prepare the initial import commit date and N-1 change commits
$dates = Get-RandomDates -Start $start -End $now -Count $Commits
$dates = $dates | Sort-Object

# Create initial import commit (backdated to earliest date)
$initialDate = $dates[0]
Write-Info ("Creating initial backdated commit at {0}" -f $initialDate)
git add -A
$env:GIT_AUTHOR_DATE = $initialDate.ToString("r")
$env:GIT_COMMITTER_DATE = $initialDate.ToString("r")
git commit -m "Initial import" --allow-empty | Out-Null
Remove-Item Env:\\GIT_AUTHOR_DATE -ErrorAction SilentlyContinue
Remove-Item Env:\\GIT_COMMITTER_DATE -ErrorAction SilentlyContinue

# Generate N-1 subsequent commits with simple changes
if ($Commits -gt 1) {
    if (-not (Test-Path $ChangeFile)) {
        "# Autogenerated change log" | Out-File -FilePath $ChangeFile -Encoding UTF8 -Append
    }
    for ($i = 1; $i -lt $Commits; $i++) {
        $d = $dates[$i]
        $stamp = $d.LocalDateTime.ToString("yyyy-MM-dd HH:mm:ss")
        $changeLine = ("- Minor housekeeping change {0} (commit {1})" -f $stamp, ($i + 1))
        Add-Content -Path $ChangeFile -Value $changeLine
        git add $ChangeFile
        $env:GIT_AUTHOR_DATE = $d.ToString("r")
        $env:GIT_COMMITTER_DATE = $d.ToString("r")
        git commit -m ("Chore: update notes ({0})" -f $stamp) | Out-Null
        Remove-Item Env:\\GIT_AUTHOR_DATE -ErrorAction SilentlyContinue
        Remove-Item Env:\\GIT_COMMITTER_DATE -ErrorAction SilentlyContinue
        Write-Info ("Created commit {0}/{1} at {2}" -f ($i + 1), $Commits, $d)
    }
}

if ($Remote -and $Remote.Trim().Length -gt 0) {
    Write-Info ("Configuring remote 'origin' => {0}" -f $Remote)
    $hasOrigin = $false
    try {
        git remote get-url origin *> $null
        if ($LASTEXITCODE -eq 0) { $hasOrigin = $true }
    } catch {
        $hasOrigin = $false
    }
    if ($hasOrigin) {
        git remote set-url origin $Remote
    } else {
        git remote add origin $Remote
    }
    Write-Info "Pushing to remote..."
    git push -u origin $Branch
} else {
    Write-Warn "Remote not provided. Skipping push. Provide -Remote https://github.com/<user>/<repo>.git to push."
}

Write-Info "Done."

